services:
  pihole:
    container_name: pihole_prj
    image: pihole/pihole:latest
    hostname: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    networks:
      default:
       ipv4_address: 172.28.0.3
    environment:
      TZ: 'Asia/Ho_Chi_Minh'
      FTLCONF_webserver_api_password: '${PIHOLE_PASSWORD}'
      FTLCONF_dns_listeningMode: 'all' 	
      FTLCONF_dns_upstreams: 'unbound;unbound'
      #PIHOLE_DNS_1: 127.28.0.2
      #PIHOLE_DNS_2: 127.28.0.2
      PIHOLE_DNS_1: unbound
      PIHOLE_DNS_2: unbound
      TAIL_FTL_LOG: 0
    volumes:
      - ./etc-pihole:/etc/pihole
      - /var/log/pihole:/var/log/pihole
      #- ./etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  unbound:
    image: klutchell/unbound:latest
    container_name: unbound_prj
    hostname: unbound
    networks:
      default:
#    volumes:
#      - ./etc-unbound:/etc/unbound
#    command: >
#      sh -c "unbound-anchor"
#    healthcheck:
#      test: ["CMD", "dig", "-p", "53", "dnssec.works", "@127.0.0.1"]
#      interval: 30s
#      timeout: 30s
#      retries: 3
#      start_period: 30s
    restart: unless-stopped
    # Pi-hole will be configured to use this as upstream DNS

#  samba:
#    image: dperson/samba
#    environment:
#      - USERID=1000
#      - GROUPID=1000
#      - TZ='Asia/Ho_Chi_Minh'
#    volumes:
#      - /mnt/storage:/mnt/storage:rw
#    command: >
#      -u "bame;bame" 
#      -u "be;be"
#      -s "bame;/mnt/storage/bame;no;no;no;bame"
#      -s "be;/mnt/storage/be;no;no;no;be"
#      -s "public;/mnt/storage/public;yes;no;yes"
#    ports:
#      - "139:139"
#      - "445:445"
#    restart: unless-stopped

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
          gateway: 172.28.0.1
