services:
  # 1. SERVER GỐC (Bắt buộc phải có để chạy giao diện Web)
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release # Dùng đúng ảnh server
    volumes:
      - /mnt/ssd/immich/upload:/usr/src/app/upload
      - /mnt/ssd/drivedata:/mnt/media/photos:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - "2283:2283"
    depends_on:
      - redis
      - database
    restart: unless_stopped
    deploy:
      resources:
        limits:
          memory: 400M

  # 2. JOB DAEMON (Chạy song song để tối ưu cho Pi 3)
  immich-job-daemon:
    container_name: immich_job_daemon
    image: ghcr.io/alternativniy/immich-job-daemon:latest
    environment:
      - IMMICH_URL=http://immich-server:2283/api # Trỏ đúng về service core ở trên
      - API_KEY=${MY_IMMICH_KEY} # Lấy từ .env sau khi đã đăng ký web
      - MAX_CONCURRENT_JOBS=1
      - POLL_INTERVAL=30
    depends_on:
      - immich-server
    restart: unless-stopped

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine
    deploy:
      resources:
        limits:
          memory: 64M
    restart: unless-stopped

  database:
    container_name: immich_postgres
    user: "999:999"
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - /mnt/ssd/docker/immich/postgres:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 200M
    restart: unless-stopped
